services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - internal

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      - CI_ENVIRONMENT=development
    networks:
      - internal

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge
